# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_todos', '0006_remove_todolisttemplate_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
